name: deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    permissions:
      contents: write
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3.0.2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: flutter build web --web-renderer html

      - name: 🛥 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: cgutierr-zgz
          user_email: carlosgutimo.3d@gmail.com
          publish_branch: master
